---
- hosts: tag_type_app
  tasks:
  - name: Add host to ELB
    local_action:
      module: ec2_elb
      ec2_region: "us-east-1"
      instance_id: "{{ ec2_id }}"  # instance_id from Ansible Facts
      ec2_elbs: "{{ elb_name }}"
      state: present
      wait: yes
      wait_timeout: 60
    ignore_errors: yes
