---
- hosts: ansible-tower
  connection: local
  tasks:
    - name: Job Template to launch a Job Template with update on launch inventory set (as a workaround, Workflow Job Template do that in Tower 3.1)
      uri:
        url: https://{{ ansible_tower_ip }}/api/v1/job_templates/{{ job_template_id }}/launch/
        method: POST
        user: {{ ansible_tower_user }}
        password: {{ ansible_tower_password }}
        body:
          extra_vars: "launched_from: Ansible Tower"
        body_format: json
        validate_certs: False
        HEADER_Content-Type: "application/json"
        status_code: 200, 201
