---
galaxy_info:
  author: "Drew Bomhof"
  company: Red Hat, Inc.
  license: license (Apache)
  min_ansible_version: 2.2
  platforms:
   - name: EL
     versions:
      - 7

   - name: Fedora
     versions:
      - 25
      - 26
   - name: Ubuntu
     versions:
      - xenial
      - precise
  galaxy_tags: [manageiq, cloudforms, automate, rhel]
dependencies: []
